remote_theme: "mmistakes/minimal-mistakes"
author: Anand Rajneesh
author_email: anandrajneesh@outlook.com
defaults:
  # _docs
  - scope:
      path: ""
      type: posts
    values:
      sidebar:
        nav: "posts"
